# Application name
spring.application.name=eureka-server

# Server port
server.port=8761

# Eureka Server Configuration
eureka.instance.hostname=localhost

# Since this is a server, it should not register itself
eureka.client.register-with-eureka=false

# And it should not fetch registry info
eureka.client.fetch-registry=false

# Service URL (points to itself)
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/

# Disable self-preservation (optional, for dev only)
eureka.server.enable-self-preservation=false

# Eviction interval (optional tuning)
eureka.server.eviction-interval-timer-in-ms=4000